<a href="https://colab.research.google.com/github/sztomo5/data-science-bootcamp/blob/main/wprowadzenie/Bootcamp_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [2]:
np.__version__

'1.22.4'

In [ ]:
help(np.array)

In [5]:
x = np.array([1, 3])

In [7]:
x

array([1, 3])

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size


2

In [11]:
x.dtype

dtype('int64')

In [12]:
y = np.array([1.3, 2.6, 3.0])

In [13]:
y.size

3

In [14]:
y.shape

(3,)

In [15]:
y.dtype

dtype('float64')

In [23]:
x = np.array([[1, 2], [-3, 1]])

In [24]:
print(x)

[[ 1  2]
 [-3  1]]


In [25]:
x.shape


(2, 2)

In [26]:
y = np.array([[2, 4], [-4, 7]])

In [27]:
y.shape

(2, 2)

In [28]:
y.ndim

2

In [29]:
y.shape

(2, 2)

In [30]:
y.size

4

In [32]:
y.dtype

dtype('int64')

In [35]:
z = np.array([[1, 3, 5], [7, 3, 6]])

In [36]:
z.shape

(2, 3)

In [37]:
z.ndim

2

In [38]:
z.size

6

In [39]:
z.ndim

2

In [40]:
z.size

6

In [41]:
z.shape

(2, 3)

In [42]:
z

array([[1, 3, 5],
       [7, 3, 6]])

In [43]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]]])

In [44]:
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [45]:
x.ndim

3

In [46]:
x.size

12

In [47]:
x.shape

(2, 2, 3)

In [48]:
x.dtype

dtype('int64')

In [49]:
A = np.array([1, 2, 3])

In [50]:
A.ndim

1

In [51]:
A.dtype

dtype('int64')

In [52]:
A.size

3

In [53]:
A.shape

(3,)

In [54]:
A = np.array([1, 3, 2], dtype='float')

In [55]:
A.dtype

dtype('float64')

In [56]:
A

array([1., 3., 2.])

In [57]:
A = np.array([True, False])

In [58]:
A.dtype

dtype('bool')

In [59]:
A.size

2

In [61]:
A.ndim

1

In [62]:
A.shape

(2,)

In [63]:
A.dtype

dtype('bool')

In [68]:
A = np.array([24, 120, 230], dtype=np.uint8)

In [69]:
A

array([ 24, 120, 230], dtype=uint8)

In [70]:
print(A)

[ 24 120 230]


In [71]:
A.dtype

dtype('uint8')

In [75]:
z = np.zeros(shape=(4, 10), dtype=int)

In [76]:
print(z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [77]:
np.ones(shape=(10, 10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [78]:
np.full(shape=(5, 5), fill_value=4, dtype=int)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [80]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x = np.arange(20)

In [82]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [83]:
x.size

20

In [84]:
x.dtype

dtype('int64')

In [85]:
x.shape

(20,)

In [87]:
x.ndim

1

In [88]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [89]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [93]:
np.arange(0, 1, 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [98]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [99]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [109]:
x = np.arange(30)

In [101]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
x.reshape((2, 3, 5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [112]:
x.reshape((-1, 5)).shape

(6, 5)

In [113]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [114]:
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [115]:
A + B

array([6, 0, 7, 4])

In [116]:
A - B 

array([0, 2, 1, 0])

In [117]:
A


array([3, 1, 4, 2])

In [118]:
A + 3


array([6, 4, 7, 5])

In [119]:
s = np.array([[[2, 3, 4], [2, 6, 4]], [[2, 4, 6], [6, 4, 5]]])

In [121]:
s.ndim

3

In [122]:
s.shape


(2, 2, 3)

In [123]:
s.dtype

dtype('int64')

In [124]:
s.size


12

In [125]:
s + 2

array([[[4, 5, 6],
        [4, 8, 6]],

       [[4, 6, 8],
        [8, 6, 7]]])

In [126]:
s ? 2

SyntaxError: ignored

In [127]:
S / 2

NameError: ignored

In [128]:
s / 2

array([[[1. , 1.5, 2. ],
        [1. , 3. , 2. ]],

       [[1. , 2. , 3. ],
        [3. , 2. , 2.5]]])

In [129]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [132]:
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [131]:
print(X * Y)

[[6 0]
 [2 0]]


In [133]:
print(np.dot(X, Y))

[[  3   6]
 [-12   0]]


In [3]:
np.random.seed(0)
np.random.randn()

1.764052345967664

In [4]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [6]:
np.random.randn(3, 10, 4)

array([[[ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
        [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
        [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
        [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
        [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056],
        [ 0.12898291,  1.13940068, -1.23482582,  0.40234164],
        [-0.68481009, -0.87079715, -0.57884966, -0.31155253],
        [ 0.05616534, -1.16514984,  0.90082649,  0.46566244],
        [-1.53624369,  1.48825219,  1.89588918,  1.17877957],
        [-0.17992484, -1.07075262,  1.05445173, -0.40317695]],

       [[ 1.22244507,  0.20827498,  0.97663904,  0.3563664 ],
        [ 0.70657317,  0.01050002,  1.78587049,  0.12691209],
        [ 0.40198936,  1.8831507 , -1.34775906, -1.270485  ],
        [ 0.96939671, -1.17312341,  1.94362119, -0.41361898],
        [-0.74745481,  1.92294203,  1.48051479,  1.86755896],
        [ 0.90604466, -0.86122569,  1.91006495, -0.26800337],
      

In [10]:
np.random.rand()

0.9527916569719446

In [11]:
np.random.rand(10, 5)

array([[0.68748828, 0.21550768, 0.94737059, 0.73085581, 0.25394164],
       [0.21331198, 0.51820071, 0.02566272, 0.20747008, 0.42468547],
       [0.37416998, 0.46357542, 0.27762871, 0.58678435, 0.86385561],
       [0.11753186, 0.51737911, 0.13206811, 0.71685968, 0.3960597 ],
       [0.56542131, 0.18327984, 0.14484776, 0.48805628, 0.35561274],
       [0.94043195, 0.76532525, 0.74866362, 0.90371974, 0.08342244],
       [0.55219247, 0.58447607, 0.96193638, 0.29214753, 0.24082878],
       [0.10029394, 0.01642963, 0.92952932, 0.66991655, 0.78515291],
       [0.28173011, 0.58641017, 0.06395527, 0.4856276 , 0.97749514],
       [0.87650525, 0.33815895, 0.96157015, 0.23170163, 0.94931882]])

In [13]:
np.random.randint(10, 100)

14

In [15]:
np.random.randint(low=1, high=15, size=10)

array([ 5, 13,  2,  8,  7, 10,  5,  2,  6, 10])

In [19]:
np.random.choice([1, 5, 8, 2, 4, 7])

2

In [27]:
np.random.choice(['python', 'java', 'SQL'])

'python'

In [28]:
data = np.arange(10)

In [29]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.random.shuffle(data)

In [31]:
data

array([6, 5, 2, 9, 0, 7, 1, 4, 8, 3])

In [32]:
np.exp(1)

2.718281828459045

In [33]:
np.exp(2)

7.38905609893065

In [34]:
np.exp(1)

2.718281828459045

In [35]:
np.sqrt(25)

5.0

In [37]:
np.all([1, 5, 0, 2, 8, -1])

False

In [38]:
np.any([1, 5, 3 ,7, 4])

True

In [40]:
np.all([0, 0, 0, 1, 0])

False

In [44]:
A = np.random.rand(5)

In [45]:
A

array([0.41137241, 0.35927142, 0.39949891, 0.30183088, 0.77521978])

In [46]:
np.argmax(A)

4

In [47]:
np.argmin(A)

3

In [48]:
B = np.arange(20)

In [49]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
B = np.random.rand(20)

In [51]:
B

array([0.92621293, 0.32531031, 0.95287067, 0.0139484 , 0.53346568,
       0.30458203, 0.88286   , 0.25062272, 0.67741183, 0.81042409,
       0.43214805, 0.75213452, 0.82960225, 0.37903377, 0.09654961,
       0.25613958, 0.59193516, 0.4764772 , 0.48793457, 0.45851455])

In [52]:
B[np.argmax(B)]

0.9528706723868426

In [53]:
np.argsort(B)

array([ 3, 14,  7, 15,  5,  1, 13, 10, 19, 17, 18,  4, 16,  8, 11,  9, 12,
        6,  0,  2])

In [54]:
np.max(B)

0.9528706723868426

In [56]:
np.max(B)

0.9528706723868426

In [57]:
np.min(B)

0.013948395933415347

In [58]:
np.mean(B)

0.5219088956600241

In [60]:
n = np.arange(5)

In [61]:
np.mean(n)

2.0

In [62]:
n


array([0, 1, 2, 3, 4])

In [63]:
np.median(n)

2.0

In [64]:
n = np.array([1, 5, 7, 3, 5])
n
np.mean(n)
np.median(n)

5.0

In [65]:
n

array([1, 5, 7, 3, 5])

In [66]:
np.median(n)

5.0

In [67]:
np.mean(n)

4.2

In [68]:
 np.std(n)

2.039607805437114

In [69]:
np.std(B)

0.26873660787995285

In [3]:
import numpy as np
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
A = np.arange(20)

In [6]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
A[10]

10

In [8]:
A[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
A[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
A[[0, 3, 6]]

array([0, 3, 6])

In [12]:
A[10:15]

array([10, 11, 12, 13, 14])

In [14]:
A = A.reshape(4, 5)

In [15]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
A[1]

array([5, 6, 7, 8, 9])

In [18]:
A[:,1]

array([ 1,  6, 11, 16])

In [20]:
A[2,3]

13

In [21]:
A[1:3, 2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [22]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
A[1,1]

6

In [25]:
A[1,1] = 8

In [26]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  8,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  8,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 8 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  for num in row:
    print(num)

In [30]:
for row in A:
  print(row[0])

0
5
10
15


In [31]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
8
7
8
9
10
11
12
13
14
15
16
17
18
19


In [32]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  8,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
B = np.array([[[1, 2],
               [3, 2]],
               [[4, 5],
                [2, 6]]])

In [37]:
B

array([[[1, 2],
        [3, 2]],

       [[4, 5],
        [2, 6]]])

In [38]:
B.reshape(2, 4)

array([[1, 2, 3, 2],
       [4, 5, 2, 6]])

In [39]:
B


array([[[1, 2],
        [3, 2]],

       [[4, 5],
        [2, 6]]])

In [40]:
B.ravel()

array([1, 2, 3, 2, 4, 5, 2, 6])

In [41]:
B

array([[[1, 2],
        [3, 2]],

       [[4, 5],
        [2, 6]]])

In [43]:
list(B.flat)

[1, 2, 3, 2, 4, 5, 2, 6]

In [44]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  8,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  8, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [46]:
A = np.arange(-10, 10, 0.5)

In [47]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [48]:
A.reshape(10, -1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [49]:
A.shape

(40,)

In [50]:
A.reshape(10, 4)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [51]:
A.shape

(40,)

In [52]:
A > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [53]:
A > -1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [54]:
A < 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [56]:
np.bitwise_and(A > -5, A < 5)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [57]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [58]:
np.bitwise_or(A < -5, A > 5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])